image: node:18

stages:
  - install
  - test
  - build
  - deploy

cache:
  paths:
    - node_modules/
    - .npm/

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"

# Install dependencies
install:
  stage: install
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 hour

# Run tests with JUnit output
test:unit:
  stage: test
  dependencies:
    - install
  script:
    - npm run test:run -- --reporter=junit --reporter=default --outputFile=junit.xml
  artifacts:
    when: always
    paths:
      - junit.xml
    reports:
      junit: junit.xml
    expire_in: 1 week

# Generate test coverage
test:coverage:
  stage: test
  dependencies:
    - install
  script:
    - npm run test:coverage
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    paths:
      - coverage/
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
    expire_in: 1 week

# Type checking
type-check:
  stage: test
  dependencies:
    - install
  script:
    - npm run type-check

# Build library
build:library:
  stage: build
  dependencies:
    - install
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 week

# Build Storybook
build:storybook:
  stage: build
  dependencies:
    - install
  script:
    - npm run build:storybook
  artifacts:
    paths:
      - storybook-static/
    expire_in: 1 week

# Generate TypeDoc documentation
build:docs:
  stage: build
  dependencies:
    - install
  script:
    - npm run docs
    - cp DOCUMENTATION.md docs/DOCUMENTATION.md
  artifacts:
    paths:
      - docs/
    expire_in: 1 week

# Deploy to GitLab Pages
pages:
  stage: deploy
  dependencies:
    - build:library
    - build:storybook
    - build:docs
    - test:coverage
  script:
    - mkdir -p public
    - cp -r storybook-static public/storybook
    - cp -r docs public/docs
    - cp -r coverage public/coverage
    - cp -r dist public/dist
    - |
      cat > public/index.html << 'EOF'
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Preact Components System</title>
        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            line-height: 1.6;
            color: #333;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 20px;
          }
          .container {
            max-width: 800px;
            background: white;
            border-radius: 12px;
            padding: 40px;
            box-shadow: 0 20px 60px rgba(0,0,0,0.3);
          }
          h1 {
            color: #667eea;
            margin-bottom: 10px;
            font-size: 2.5rem;
          }
          .version {
            color: #666;
            margin-bottom: 30px;
            font-size: 0.9rem;
          }
          .links {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            margin-top: 30px;
          }
          .link-card {
            padding: 20px;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            text-decoration: none;
            border-radius: 8px;
            transition: transform 0.2s, box-shadow 0.2s;
            display: block;
          }
          .link-card:hover {
            transform: translateY(-5px);
            box-shadow: 0 10px 30px rgba(102, 126, 234, 0.4);
          }
          .link-card h3 {
            margin-bottom: 8px;
            font-size: 1.2rem;
          }
          .link-card p {
            font-size: 0.9rem;
            opacity: 0.9;
          }
          .stats {
            display: flex;
            gap: 20px;
            margin: 30px 0;
            flex-wrap: wrap;
          }
          .stat {
            flex: 1;
            min-width: 150px;
            padding: 15px;
            background: #f8f9fa;
            border-radius: 8px;
            text-align: center;
          }
          .stat-value {
            font-size: 1.5rem;
            font-weight: bold;
            color: #667eea;
          }
          .stat-label {
            font-size: 0.85rem;
            color: #666;
            margin-top: 5px;
          }
        </style>
      </head>
      <body>
        <div class="container">
          <h1>🎨 Preact Components System</h1>
          <p class="version">Version 1.0.1 • Build: ${CI_COMMIT_SHORT_SHA}</p>
          
          <div class="stats">
            <div class="stat">
              <div class="stat-value">40 kB</div>
              <div class="stat-label">Bundle Size</div>
            </div>
            <div class="stat">
              <div class="stat-value">77/77</div>
              <div class="stat-label">Tests Passing</div>
            </div>
            <div class="stat">
              <div class="stat-value">TypeScript</div>
              <div class="stat-label">Full Type Safety</div>
            </div>
          </div>

          <div class="links">
            <a href="./storybook/" class="link-card">
              <h3>📚 Storybook</h3>
              <p>Interactive component documentation and examples</p>
            </a>
            
            <a href="./docs/" class="link-card">
              <h3>📖 API Docs</h3>
              <p>Complete TypeDoc API reference</p>
            </a>
            
            <a href="./coverage/" class="link-card">
              <h3>🧪 Coverage</h3>
              <p>Test coverage reports and metrics</p>
            </a>
            
            <a href="./dist/" class="link-card">
              <h3>📦 Build Artifacts</h3>
              <p>Production library build files</p>
            </a>
          </div>

          <div style="margin-top: 40px; padding-top: 30px; border-top: 1px solid #e0e0e0; text-align: center; color: #666;">
            <p>
              <a href="https://github.com/prachwal/preact-components-system" style="color: #667eea; text-decoration: none;">
                GitHub Repository
              </a>
              •
              <a href="./docs/DOCUMENTATION.html" style="color: #667eea; text-decoration: none;">
                Full Documentation
              </a>
            </p>
          </div>
        </div>
      </body>
      </html>
      EOF
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# Optional: Deploy to npm (triggered manually or on tags)
publish:npm:
  stage: deploy
  dependencies:
    - build:library
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - npm publish
  rules:
    - if: $CI_COMMIT_TAG
      when: manual
  only:
    - tags
